/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./stitch_riskvision_ai_intelligence_platform/index.html",
    "./stitch_riskvision_ai_intelligence_platform/dashboard/index.html",
    "./stitch_riskvision_ai_intelligence_platform/dashboard/src/**/*.{js,ts,jsx,tsx}",
    "./stitch_riskvision_ai_intelligence_platform/js/**/*.js",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        navy: {
          950: '#0B1120',
          900: '#0F172A',
          850: '#172033',
          800: '#1E293B',
          750: '#27354A',
          700: '#334155',
          600: '#475569',
        },
        brand: {
          50:  '#EFF6FF',
          100: '#DBEAFE',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
        },
        accent: {
          cyan:    '#06B6D4',
          emerald: '#10B981',
          amber:   '#F59E0B',
          rose:    '#F43F5E',
          violet:  '#8B5CF6',
        },
        surface: {
          DEFAULT: '#10131b',
          dark:    '#0F172A',
          card:    '#1E293B',
          border:  '#334155',
          input:   '#0B1120',
        },
        primary: '#adc6ff',
        'primary-fixed-dim': '#60A5FA',
        'on-primary': '#FFFFFF',
        'on-surface': '#e0e2ed',
        'on-surface-variant': '#c1c6d7',
        tertiary: '#00dbe9',
        secondary: '#d1bcff',
        "outline-variant": "#414755",
        "secondary-container": "#7000ff",
        "on-secondary-fixed-variant": "#5700c9",
        "surface-container-high": "#272a32",
        "inverse-primary": "#005bc1",
        "on-primary-fixed": "#001a41",
        "on-secondary-container": "#ddcdff",
        "secondary-fixed-dim": "#d1bcff",
        "surface-container-highest": "#31353d",
        "on-background": "#e0e2ed",
        "on-secondary-fixed": "#23005b",
        "on-tertiary-fixed-variant": "#004f54",
        "surface-container-lowest": "#0b0e16",
        "surface-container": "#1c2028",
        "tertiary-container": "#00a0aa",
        "inverse-on-surface": "#2d3039",
        "surface-variant": "#31353d",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed": "#7df4ff",
        "on-primary-container": "#00285c",
        "tertiary-fixed-dim": "#00dbe9",
        "surface-tint": "#adc6ff",
        "on-tertiary-container": "#002f33",
      },
      boxShadow: {
        'card': '0 4px 20px -2px rgba(0, 0, 0, 0.4), 0 2px 6px -1px rgba(0, 0, 0, 0.2)',
        'card-hover': '0 10px 30px -4px rgba(59, 130, 246, 0.15), 0 4px 12px -2px rgba(0, 0, 0, 0.4)',
        'glow-blue': '0 0 20px rgba(59, 130, 246, 0.35)',
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "margin-tablet": "32px",
        "margin-desktop": "64px",
        unit: "8px"
      },
      fontFamily: {
        "display-lg": ["Geist"],
        "body-lg": ["Inter"],
        "headline-lg": ["Geist"],
        "display-xl": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "body-md": ["Inter"],
        "label-mono": ["JetBrains Mono"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-xl": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400"}],
        "label-mono": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
};
