import React from 'react';
import { useAIInsights } from '../../../hooks/useDashboard';
import WidgetWrapper from '../Common/WidgetWrapper';
import Badge from '../../common/Badge';

export const AIInsightsWidget: React.FC = () => {
  const { data: insights, isLoading, isError, refetch } = useAIInsights(2);

  return (
    <WidgetWrapper
      title="NEURAL INSIGHT FEED"
      subtitle="Dynamic natural language risk explanations generated by local LLM hooks"
      isLoading={isLoading}
      isError={isError}
      onRetry={refetch}
    >
      <div className="space-y-3 py-1 flex-1 flex flex-col justify-center">
        {insights?.insights.map((item, idx) => (
          <div
            key={idx}
            className="p-3 border border-slate-800 bg-cyber-950/30 rounded-lg hover:border-neon-blue/20 transition-all duration-200"
          >
            <div className="flex items-center justify-between gap-2 mb-2 font-mono text-[10px]">
              <span className="font-bold text-slate-300">{item.project_name}</span>
              <div className="flex items-center gap-1.5">
                <span className="text-neon-pink">{(item.failure_probability * 100).toFixed(0)}% Fail</span>
                <Badge label={item.risk_level} />
              </div>
            </div>
            <p className="text-[10px] text-slate-400 font-mono leading-relaxed">
              {item.insight}
            </p>
          </div>
        ))}
      </div>
    </WidgetWrapper>
  );
};
export default AIInsightsWidget;
